{
 "title": "全国速率监测（地级市版）",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province",
    "label": "省份",
    "query": "安徽, 北京, 重庆, 福建, 甘肃, 广东, 广西, 贵州, 海南, 河北, 黑龙江, 河南, 湖北, 湖南, 江苏, 江西, 吉林, 辽宁, 内蒙古, 宁夏, 青海, 陕西, 山东, 上海, 山西, 四川, 天津, 新疆, 西藏, 云南, 浙江"
   },
   { "name": "city", "label": "城市" }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(idc_ping_monitor{})", "legendFormat": "监控城市" },
    { "expr": "count(idc_ping_monitor{} == 0)", "legendFormat": "无法连接城市" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(idc_ping_monitor{} == 0) by (province)",
     "legendFormat": "{{instance}}-{{ip}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(idc_ping_monitor{province=~\"$province\",city=~\"$city\"} == 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "电信延迟一览",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idc_ping_monitor{province=~\"$province\",isp='电信',city=~\"$city\"}",
     "legendFormat": "{{instance}}-{{ip}}"
    }
   ]
  },
  {
   "title": "联通延迟一览",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "idc_ping_monitor{province=~\"$province\",isp='联通',city=~\"$city\"}",
     "legendFormat": "{{instance}}-{{ip}}"
    }
   ]
  },
  {
   "title": "移动延迟一览",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "idc_ping_monitor{province=~\"$province\",isp='移动',city=~\"$city\"}",
     "legendFormat": "{{instance}}-{{ip}}"
    }
   ]
  }
 ]
}